Repository googleapis/google-cloud-node, pull requests merged in 2020-08, with the labels that each got.

#3024 fix: add incomplete results view
  bin/generate-readme.js
Labels: cla: yes

#3027 docs: update libraries list
  README.md
  libraries.json
  synth.metadata
Labels: cla: yes, context: none

#3029 docs: update doc links for cloud functions
  libraries.json
  synth.metadata
Labels: cla: yes, context: none

#3030 docs: remove IRM from the list of available APIs
  README.md
  libraries.json
  synth.metadata
Labels: cla: yes, context: none

#3031 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full
