Repository googleapis/google-cloud-node, pull requests merged in 2021-04, with the labels that each got.

#3080 docs: updating IOT team in README
  libraries.json
  synth.metadata
Labels: cla: yes, context: none

#3081 docs: changes to README (nit)
  libraries.json
  synth.metadata
Labels: cla: yes, context: none

#3082 docs: updated meta information for libraries
  libraries.json
  synth.metadata
Labels: cla: yes, context: none

#3083 docs: updates to README
  README.md
  libraries.json
  synth.metadata
Labels: cla: yes, context: none

#3085 chore: update codeowner_team for dataproc
  libraries.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#3086 chore: update generated list of libraries
  libraries.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#3088 chore: updates to libraries.json file
  libraries.json
  synth.metadata
Labels: cla: yes, context: none

#3089 docs: update libraries.json
  libraries.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#3090 chore: add sync-repo-settings config
  .github/sync-repo-settings.yaml
Labels: cla: yes

#3091 chore: add "default_version": "v1" to libraries.json
  libraries.json
  synth.metadata
Labels: cla: yes, context: none
